{
 "title": "Donations",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Count #donation",
   "type": "gauge",
   "description": "SELECT COUNT(*) FROM donations.donation_transactions\nWHERE is_campaign_active=1",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "db_training",
     "rawSql": "SELECT COUNT(*) FROM donations.donation_transactions\nWHERE is_campaign_active=1"
    }
   ]
  },
  {
   "title": "Total amount of donations",
   "type": "gauge",
   "description": "SELECT \n    SUM(total_amount) AS total_donation_amount\nFROM \n    donation_transactions\nWHERE is_campaign_active=1;",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "db_training",
     "rawSql": "SELECT \n    SUM(total_amount) AS total_donation_amount\nFROM \n    donation_transactions\nWHERE is_campaign_active=1;\n"
    }
   ]
  },
  {
   "title": "Best city, organisation donation",
   "type": "gauge",
   "description": "SELECT \n    city,\n    organization,\n    SUM(total_amount) AS total_donation_amount\nFROM \n    donation_transactions\nWHERE is_campaign_active=1\nGROUP BY \n    city,organization\nORDER BY \n    total_donation_amount DESC\nLIMIT 1;\n",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "db_training",
     "rawSql": "SELECT \n    city,\n    organization,\n    SUM(total_amount) AS total_donation_amount\nFROM \n    donation_transactions\nWHERE is_campaign_active=1\nGROUP BY \n    city,organization\nORDER BY \n    total_donation_amount DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "Last 35s of total amount of donations per city",
   "type": "bargauge",
   "description": "SELECT \n    city,\n    SUM(total_amount) AS total_donation_amount\nFROM \n    donation_transactions\nWHERE \n    transaction_date > CONVERT_TZ(NOW(), 'UTC', 'Europe/Paris') - INTERVAL 35 SECOND\n    AND is_campaign_active=1\nGROUP BY \n    city\nORDER BY total_donation_amount desc;",
   "gridPos": { "h": 5, "w": 9, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "db_training",
     "rawSql": "SELECT \n    city,\n    SUM(total_amount) AS total_donation_amount\nFROM \n    donation_transactions\nWHERE \n    transaction_date > CONVERT_TZ(NOW(), 'UTC', 'Europe/Paris') - INTERVAL 35 SECOND\n    AND is_campaign_active=1\nGROUP BY \n    city\nORDER BY city ASC;"
    }
   ]
  },
  {
   "title": "Amount of donations per geo loc city",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "dataset": "db_training",
     "rawSql": "SELECT \n    city,\n    latitude,\n    longitude,\n    SUM(total_amount) AS total_donation_amount\nFROM \n    donation_transactions\nWHERE is_campaign_active = 1\nGROUP BY \n    city"
    }
   ]
  },
  {
   "title": "Total amount of donations per organization",
   "type": "barchart",
   "description": "SELECT \n    organization,\n    SUM(total_amount) AS total_donation_amount\nFROM \n    donation_transactions\nWHERE is_campaign_active=1\nGROUP BY \n    organization\nORDER BY \n    total_donation_amount DESC;\n",
   "gridPos": { "h": 15, "w": 6, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "dataset": "db_training",
     "rawSql": "SELECT \n    organization,\n    SUM(total_amount) AS total_donation_amount\nFROM \n    donation_transactions\nWHERE is_campaign_active=1\nGROUP BY \n    organization\nORDER BY \n    total_donation_amount DESC;\n"
    }
   ]
  },
  {
   "title": "Last 28s of total amount of donations per organization",
   "type": "bargauge",
   "description": "SELECT \n    organization,\n    SUM(total_amount) AS total_donation_amount\nFROM \n    donation_transactions\nWHERE \n    transaction_date > CONVERT_TZ(NOW(), 'UTC', 'Europe/Paris') - INTERVAL 28 SECOND\n    AND is_campaign_active=1\nGROUP BY \n    organization",
   "gridPos": { "h": 13, "w": 9, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "db_training",
     "rawSql": "SELECT \n    organization,\n    SUM(total_amount) AS total_donation_amount\nFROM \n    donation_transactions\nWHERE \n    transaction_date > CONVERT_TZ(NOW(), 'UTC', 'Europe/Paris') - INTERVAL 28 SECOND\n    AND is_campaign_active=1\nGROUP BY \n    organization"
    }
   ]
  }
 ]
}